### ISSUE TITLE
Dynamically created event handlers do not work on C++ platform when Button is not initialized with dimensions

### ISSUE THREAD

**Issue by dreamycactus** [RealyUniqueName/StablexUI#180]
Title pretty much contains problem and temporary workaround.

This code
```
 var b = UIBuilder.create(Button, {
//                    w : 50,
//                    h : 50,
                    text : 'hello',
                    skinName : 'skinName'
                }); 
                b.addEventListener(MouseEvent.CLICK, loadLevel.bind(path) );
```
Works as expected on Flash platform, as the button is just initialized with some default dimensions. However, on C++, the event does not trigger. As soon as a the dimensions are added, it works. It took me a long time to track down the reason for this... 

Just as a side note, onInitialize and onCreate do not affect the problem.

**Comment by RealyUniqueName** [comment]
What versions of StablexUI, OpenFL, Haxe and hxcpp do you use?
I test with lastest versions and everything seems to work fine.

**Comment by dreamycactus** [comment]
Seems to work on latest for me as well. I'm not able to reproduce using the latest, so that's fine with me.
