### ISSUE TITLE
Scroll widget content is extending outside scroll widget area in HTML5

### ISSUE THREAD

**Issue by jonmoat** [RealyUniqueName/StablexUI#184]
With stablexui 1.1.4 (OpenFL 2.2.2, Haxe 3.1.3, Actuate 1.8.1) Scroll widget content is extending outside scroll widget area in HTML5 (setting overflow has no effect).

This can be reproduced by compiling the /scrolling demo sample for HTML5 target (using default OpenFL HTML5 backend) - the map spills outside as do the NME graphics (see screenshot).
![scroll](https://cloud.githubusercontent.com/assets/10533906/5742656/c3a7ca8c-9c0b-11e4-82dc-9c399c444b35.png)

Please advise.

**Comment by RealyUniqueName** [comment]
Well, it was an issue untill i made a pull request to old openfl html5 backend. Looks like Joshua did not implement scrollRect for new html5 backend. You can try html5-dom backend. 
Since it's openfl issue I'm closing this one.

**Comment by jonmoat** [comment]
OK, thanks. I'll take it up on the OpenFL forum.
I've reverted to stablexui 1.0.17 (OpenFL 2.0.1, Haxe 3.1.3, Actuate 1.7.5) and it seems OK again (it's a really useful UI system BTW).
Is there a recommended stable configuration to use with stablexui for HTML5 target?

**Comment by RealyUniqueName** [comment]
Openfl's html5 target is very unstable itself :)
So i can't recommend any solid solution.

**Comment by jonmoat** [comment]
OK, thanks.
