### ISSUE TITLE
Make a vBox containing a text auto-grow

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [RealyUniqueName/StablexUI#188]
I have a vbox with a text as a child, both have set "autoHeight" to true.

```
<VBox name="'contents'" defaults="'PopupContent'" skinName="@skin" x="@x" y="@y" w="@w" h="@h" autoHeight="true">
  <Text name="'text'" label-wordWrap="true" text="@text" widthPt="90" autoHeight="true"/>
</VBox>
```

Now I add text to the text:

```
text.text += addedText;
```

But the vbox does not grow. I also tried calling "refresh" everytime I add text, but no help.
How can I make the vbox grow with the text?

**Comment by RealyUniqueName** [comment]
Try to remove `h="@h"` attribute

**Comment by RudolfVonKrugstein** [comment]
Uh, the "h=@h" overwrites the auto size. Removing it helped, thanks!

**Comment by RealyUniqueName** [comment]
it depends on your OS (which you use to compile project) which attributes overrides another. On different systems iteration through xml attributes goes in different orders.
