### ISSUE TITLE
Move buttons/Statebuttons when pressed

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [RealyUniqueName/StablexUI#189]
Hey,

I move my buttons a little bit down-right, when they are pressed. I do the same thing for checkboxes/state buttons when they are in certain states.
Currently I am doing this by detecting if a button is pressed/state button is down from the skin and drawing the skin with an offset.
Works nice, but does not work for the label on the button.

So I need something else.

For a pushbutton I can just move the button when they are pressed and move them back when they are released.
For a state button, it is not that simple. If the button changes between states, that are both down, nothing should be moved.  So to do this in an "onPress" event, I have to know what the last state was.
Or I have to know, what the "zero-position" (the not moved position) of the button is.

Now, that are my thoughts and attempts. I am wondering: What is a good way to draw the button with a little offset (including the label) when it is pressed/it is in a "down" state?

**Comment by RealyUniqueName** [comment]
I usually shift by 1px `left`/`top` coordinates in `onPress` and by -1px in `onRelease` method. But it will shift buttons only while user is holding mouse button. 
If button's position can be changed somehow besides user presses, then i place button inside a container. And in every case except onPress/onRelease i deal with container's coordinates.

**Comment by RudolfVonKrugstein** [comment]
Ah, cool. That works, thanks!
