### ISSUE TITLE
Segmentation fault on 32 bit linux build

### ISSUE THREAD

**Issue by trsh** [RealyUniqueName/StablexUI#203]
Build from sample https://github.com/RealyUniqueName/StablexUI/tree/master/samples/demo

bin$ ./stablexui
Lib.hx:114: Warning: Graphics.beginGradientFill is not implemented
Segmentation fault (core dumped)

**Comment by trsh** [comment]
My setup:
bin$ haxelib list
actuate: [1.8.3]
box2d: [1.2.3]
haxelib_client: [3.2.0-rc.3]
haxeui: [1.7.8] 1.7.6
hscript: [2.0.4]
hxcpp: [3.2.37]
layout: [1.2.0]
lime-samples: [2.2.0]
lime: [2.3.0]
openfl-samples: [2.2.2]
openfl: 3.0.0-beta [3.0.0-beta.3]
stablexui: [1.1.4]
svg: [1.0.8]
swf: [1.8.2]
yagp: [1.1.4]

**Comment by RealyUniqueName** [comment]
it happens because of this bug: https://github.com/openfl/openfl/issues/563

**Comment by trsh** [comment]
Thanks for clearing that! Does someone know temporal workaround?

**Comment by RudolfVonKrugstein** [comment]
using an old version of lime and openfl, I guess. I am currently figuring out which ones work for me

**Comment by RudolfVonKrugstein** [comment]
Oh, I am not sure if I am really having the same problem (I am on linux64), but for me lime 2.2.2 and openfl 2.2.8 work for now.

**Comment by trsh** [comment]
Thanks. Could not help noticing that demo exported to HTML5 is full of visual bugs:

![stablexui](https://cloud.githubusercontent.com/assets/3727523/7044178/26679632-ddf9-11e4-9680-46b7e435e5f0.png)

Checks missing, radios, in some other view buttons are overlapping, etc.. Is this also due newest OpenFL. Or demo in /samples is outdated?

Browser up-to-date Chrome. This hosted version http://ui.stablex.ru/demo/demo_html5/ works perfect.

**Comment by trsh** [comment]
Visual stuff got worse with lime 2.2.2 and openfl 2.2.8 ;(

**Comment by trsh** [comment]
RudolfVonKrugstein, RealyUniqueName ???

**Comment by RealyUniqueName** [comment]
Hey, guys!
I found a workaround. You can compile in `legacy` mode to solve this and many other new issues of openfl.
Try with:
`openfl test linux -Dlegacy`

Unfortunately this still does not solve glitches with html5. But at least cpp targets look fine.

**Comment by trsh** [comment]
What libaries (stabkexui, lime, openfl, etc) is http://ui.stablex.ru/demo/demo_html5/ using? It works perfect!

**Comment by RealyUniqueName** [comment]
It's using openfl prior to 2.0.0. So i doubt you want to use the same libraries :)
