### ISSUE TITLE
Can't position widget in pixels inside relatively sized parent

### ISSUE THREAD

**Issue by trsh** [RealyUniqueName/StablexUI#208]
If parent has set size to widthPt or heightPt, child doesn't take left, top, bottom, right arguments. Is this a correct behavior?

**Comment by RealyUniqueName** [comment]
Can you show some code?

**Comment by trsh** [comment]
Using https://github.com/RealyUniqueName/StablexUI/tree/master/samples/03_position

bulid.xml
```
...
<window width="0" height="0" fullscreen="true"/>
...
```
Main.hx
```
...
UIBuilder.buildFn('position.xml')().show();
....
```
Position.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<Floating widthPt="100" heightPt="100" skin:Paint-color="0x550000">
    <!-- parent -->
    <Widget bottom="100" left="1" h="300" w="700" skin:Paint-border="1" skin:Paint-color="0x005500">
    </Widget>
</Floating>
```
"left", "top" parameters have no effect when changed. "bottom", "right" works


Also if I change back to to:
```
...
Lib.current.addChild( UIBuilder.buildFn('position.xml')() );
....
```
and
```
<Widget widthPt="100" heightPt="100" skin:Paint-color="0x550000">
    <!-- parent -->
    <Widget bottom="100" right="100" h="300" w="700" skin:Paint-border="1" skin:Paint-color="0x005500">
    </Widget>
</Widget>
```
The screen goes blank. I can't us Widget as root el with 100% width?

**Comment by RealyUniqueName** [comment]
`Floating` widget extends `Box` so it aligns children and ignores theirs position settings. If you want to cancel such behavior, set `align` property of `Floating` widget  to empty string.

As for the second question:
`Floating` is able to calculate own size with `widthPt`/`heightPt` relative to stage size, while `Widget` widthPt/heightPt works only if its parent is another StablexUI widget.

**Comment by trsh** [comment]
Ouch! Thanks for the explanation.
