### ISSUE TITLE
unifyChildren buguous with percent size parent in HTML5

### ISSUE THREAD

**Issue by trsh** [RealyUniqueName/StablexUI#209]
Sample code

```
<Box widthPt="100" heightPt="100" id="'kaka'">
	<Box id="'MainMenu2'" widthPt="100" 
            heightPt="100" 
            skin:Paint-color="0xFFFF99"
            unifyChildren="true">	
		<Button text="'Register new'" w="100" on-click="#MainMenu2.refresh();"/>
		<Button text="'List & search'" w="100"  on-click="#ViewStack(screens).show('toggles');"/>   
		<Button text="'List & search'" w="100"  on-click="#ViewStack(screens).show('toggles');"/>   
	</Box>
</Box>
```

When 'MainMenu2' first is initialized and children are added it has no size calculated. I don't know why - this._width is empty. Still _unifyChildren is called from refresh() (i guess from CREATED event) and some params like 'lastUnifyFrame' and false size for Buttons (0) are set. When it actually get's size in later logic and can arrange the children correctly it stops here (because of previous calls and data set):

```
if (UIBuilder.frameTime == this.lastUnifyFrame && this.numChildren == this.lastUnifyChildren && this.lastUnifyCount > 1) {
                return;
            }
```
and the buttons are stuck 0 size.

I could fix the bug by adding 

```
if( this.unifyChildren && (this._width != 0 && this._height != 0)){
            this._unifyChildrens();
        }
```

but I guess it's a hacky solution. As I see it 1) It has no sense to call alignElements and/or _unifyChildrens when the parent hasn't size initiated it self. 2) When parent is re-sized & refreshed, because of changes in child elements (in this case from with row.arrangeChildren?) _unifyChildrens must be always called in full length.

Best, Janis

**Comment by RealyUniqueName** [comment]
This line itself is a hacky solution because at some moment OpenFL updates introduced new bugs, so i had to make this hack to prevent endless loops in certain circumstances.

So, i think such a change is ok. At least it is not more hacky than that line already is :)
