### ISSUE TITLE
inputText buguous in HTML5

### ISSUE THREAD

**Issue by trsh** [RealyUniqueName/StablexUI#210]
To reproduce make HTML build from https://github.com/RealyUniqueName/StablexUI/tree/master/samples/04_arguments . Tried with OpenFL openfl: [2.2.8] and newest openfl 3.0.6.

Problems:
a) Text scaling horizontally when to long
b) When selecting a part of text (with mouse), it get's all black and can't see the text and overall it looks crappy.

The old sample http://ui.stablex.ru/demo/04_alert/ looks perfect :/
Where could be the problem?

Best, Janis

**Comment by trsh** [comment]
I see the old sample uses DOM for inputs. OpenFL did it again.

**Comment by RealyUniqueName** [comment]
OpenFL brought to many changes to HTML5 target, which broke a lot of things. I don't recommend using StablexUI for html5 atm.

**Comment by trsh** [comment]
Maybe you can link this issues

https://github.com/openfl/openfl/issues/690
https://github.com/openfl/openfl/issues/691

I have create on OpenFL??

**Comment by francescoagati** [comment]
with openfl 3.1 i see also text truncated with demo sample and html5 target

**Comment by RealyUniqueName** [comment]
Looks like `Text` widget autosizing does not work. This can happen due to broken text size reporting by `openfl.text.TextField`. I'll try to find workaround.

**Comment by francescoagati** [comment]
Yes only in html5 it happens

**Comment by RealyUniqueName** [comment]
I implemented a hack to workaround text truncating: https://github.com/RealyUniqueName/StablexUI/commit/db90b1e9cb6232c63e4ef5a3f85373cedad3c922

Also text input looks fixed in OpenFL 3.1.
Can you confirm this?

**Comment by francescoagati** [comment]
Yes work good with html5 now. Thanks
