### ISSUE TITLE
switching themes

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [RealyUniqueName/StablexUI#211]
Hey,

What is the best way to switch themes, by which I mean change the "skin" of all widgets?
Can I unload the skin files and load a different one, afterwards re-applying all themes to the widgets?
Or can I unload stablexui completely and reload it?

thanks!
Nathan

**Comment by trsh** [comment]
Please use https://groups.google.com/forum/#!forum/stablexui for questions. This is a issue tracker for submitting bugs, not asking advice.

**Comment by RealyUniqueName** [comment]
further discussion here: https://groups.google.com/forum/#!topic/stablexui/S9riar7IJJc
