### ISSUE TITLE
Demo app compiled for android won't show the menu

### ISSUE THREAD

**Issue by pqyptixa** [RealyUniqueName/StablexUI#214]
As the title says, the demo app compiled for android won't show the menu. It works just fine when compiled for HTML5 and Flash.

I have a similar problem with my own app:

```
package;

import openfl.display.*;
import openfl.events.*;
import ru.stablex.ui.UIBuilder;
import ru.stablex.ui.transitions.Slide;
import ru.stablex.ui.widgets.*;
import ru.stablex.ui.skins.*;
import openfl.Lib;
import Random;

class Main extends Sprite {
	
	public function new () {
		var NR_QUESTIONS:Int = 20;
		
		super ();

		Lib.current.stage.align     = StageAlign.TOP_LEFT;
		Lib.current.stage.scaleMode = StageScaleMode.NO_SCALE;

		UIBuilder.setTheme('ru.stablex.ui.themes.android4');

		UIBuilder.init();

		var skin_init:Paint = new Paint();
		var skin_true = new Paint();
		var skin_false = new Paint();
		skin_init.color = 0xa6a6a6;
		skin_true.color = 0x00ff00;
		skin_false.color = 0xff0000;
		skin_init.border = skin_true.border = skin_false.border = 1;
		skin_init.corners = [1];
	       	skin_true.corners = [1];
		skin_false.corners = [1];

		var skin2:Paint = new Paint();
		skin2.color = 0x000000;
		skin2.border = 8;
		skin2.borderColor = 0x003a00;
		skin2.alpha = 0.8;

		var txt:Array<StateButton> = new Array<StateButton>();

		var ar_ints = [for (ii in 0...NR_QUESTIONS) ii];
		Random.shuffle(ar_ints);

		for (ii in 0...NR_QUESTIONS){
			txt[ii] = UIBuilder.create(StateButton, {
				order: ['first', 'second', 'third'],
				widthPt : 100,
				h : 48
			});

			txt[ii].states.first.skin = skin_init;
			txt[ii].states.second.skin = skin_true;
			txt[ii].states.third.skin = skin_false;

			txt[ii].states.first.text = txt[ii].states.second.text = 
				txt[ii].states.third.text = (ii + 1) + ". Is this the question number " + (ar_ints[ii]+1) + "?";

			txt[ii].set('first');
		}

		var vb:Box = UIBuilder.create(Box, {
			vertical: true,
			id: 'menu',
			name: 'menu',
			widthPt: 100,
		    	children: txt
		});

		var skin3:Paint = new Paint();
		skin3.color = 0x504030;
		var sc:Scroll = UIBuilder.create(Scroll, {
			widthPt: 100,
			heightPt: 100,
			children : [vb],
		});
		sc.hBar= null;
		sc.vBar.visible= false;
		sc.vBar.w= 5;
		sc.vBar.right= 2;
		sc.vBar.visible= true;
		var skin4 = new Paint();
		skin4.color = 0x111111;
		skin4.padding = 2;
		sc.vBar.skin = skin4;

		var skinf:Paint = new Paint();
		skinf.color = 0x000000;

		var rooot:Floating = UIBuilder.create(Floating, {
			widthPt: 100,
			heightPt: 100,
			skin: skinf
		});
		rooot.show();
		rooot.addChild(sc);
		sc.refresh();
		Lib.current.addChild(rooot);

	}
}

```
Removing the android4 theme does not help.

I'm using stablexui 1.1.5 and openfl 3.3.2.

By the way, in the demo app, I can click the menu items, and at least I can see the toggles demo half-working. In my app, you can see parts of the buttons in the bottom part of the screen, so this is not a problem with the buttons themselves, but with either the Scroll or the Box elements being drawn on top of the children elements.

**Comment by RealyUniqueName** [comment]
Looks like on of the latest openfl updates introduced some bugs in DisplayObject.scrollRect. I'll try to find exact reason in next few days.

**Comment by pqyptixa** [comment]
I've been trying to compile with older versions of openfl (<3.3.1), but I couldn't...
Thanks for the pointer, I'll see if I can find anything (doubtful, but I will try).

**Comment by RealyUniqueName** [comment]
It's definitely something wrong with scrollRect. If i set scroll content size to 2000x2000 it becomes visible. If i change it to normal size - invisible.

**Comment by RealyUniqueName** [comment]
Ok, i tested with NME and it works excelent.
So you can build for html5 with OpenFL and any other target with NME. Just replace `<haxelib name="openfl" />` with `<haxelib name="nme" />` in project xml file and run build with `nme` command instead of `openfl`

**Comment by pqyptixa** [comment]
Thank you very much!
Regarding openfl, perhaps a diffing of the latest DisplayObject.hx against an older version could help?

**Comment by RealyUniqueName** [comment]
With OpenFL you can add `-Dlegacy` flag to make it work, but i don't think it makes sense because you lose all new features.

**Comment by pqyptixa** [comment]
Seems to have been fixed in openfl.
Thank you!
