### ISSUE TITLE
<u></u>tag not work on flash

### ISSUE THREAD

**Issue by LouisSong** [RealyUniqueName/StablexUI#221]
on flash target,my code is:
var t:Text = new Text();
t.label.htmlText = "<u>Hello</u>";
addChild(t);

the underline html tag not work.When change Text to openfl.text.TextField,it works.

**Comment by RealyUniqueName** [comment]
Your example works fine for me. Are you sure you didn't set `text` property after `htmlText`?
Also, you should use `UIBuilder.create()` for creating widgets instead of directly invoking constructors:
```haxe
var t:Text = UIBuilder.create(Text);
t.label.htmlText = "<u>Hello</u>";
Lib.current.addChild(t);
```

**Comment by LouisSong** [comment]
@RealyUniqueName thanks for your answer.I found that It was reformat by a textFormat.It works now!
