### ISSUE TITLE
Unable to compile examples

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [RealyUniqueName/StablexUI#226]
When I try to compile the "04_arguments" example by doing:

```
ln -s build.xml project.xml
lime test linux
```

I get: 

```
Main.hx:27: characters 30-62 : Class is not imported: 1flash
```

Is this just me, or does everyone get it? I am on ubuntu 15.10, 64 bit.

**Comment by RealyUniqueName** [comment]
There is no `1flash` in entire source code of StablexUI and examples.
"04_arguments" works fine for me.
Maybe you accidently modified some file?

**Comment by RudolfVonKrugstein** [comment]
Well, I had this issue: https://github.com/HaxeFoundation/haxe/issues/4991

And it turned out,  that the solution was installing neko from git.
Now the examples work. So sorry for the disruption.
