### ISSUE TITLE
err with lime 2.9.1

### ISSUE THREAD

**Issue by r3d9u11** [RealyUniqueName/StablexUI#227]
Hi. I have error with lime 2.9.1 (latest in haxelib repo in that time):

$openfl test neko
*** Error in `./StablexUI-Designer': free(): invalid pointer: 0x00007f2e974c2596 ***
Aborted

(it works fine with lime 2.9.0)

linux mint 17.3 x64
haxe 3.2.1
stablexui 1.1.5

**Comment by RealyUniqueName** [comment]
Try git version of StablexUI:
```
$ haxelib git stablexui https://github.com/RealyUniqueName/StablexUI.git
```
Let me know if it works for you.

**Comment by r3d9u11** [comment]
sorry, I tried v.1.1.5 (latest from haxelib repo) and dev version from git
they are both don't work with lime 2.9.1

error with version 1.1.5:

Segmentation fault

error with from git:

*** Error in `./StablexUI-Designer': free(): invalid pointer: 0x00007f2e974c2596 ***
Aborted

**Comment by RealyUniqueName** [comment]
try to build with `-debug`:
```
$ openfl test neko -debug
```
And past output here

**Comment by r3d9u11** [comment]
I have only this:

```
$ openfl test neko -debug
*** Error in `./StablexUI-Designer': free(): invalid pointer: 0x00007f46f4630596 ***
Aborted
```

(current stablexui version from git)

**Comment by RealyUniqueName** [comment]
and what if you try 
```
$ openfl test linux -debug
```
?

**Comment by r3d9u11** [comment]
as result I have log of compilation and `Segmentation fault` in the end :(

**Comment by RealyUniqueName** [comment]
This is bad. I'll try to find the reason of this issue. But i doubt it will be easy with no debug messages from lime.

**Comment by r3d9u11** [comment]
thank you, I'll try to find more info (if it possible)

**Comment by RealyUniqueName** [comment]
I've came to conclusion it's an openfl/lime bug
https://github.com/openfl/openfl/issues/1122

While it's not fixed you can use lime 2.9.0 or `-Dlegacy` to build your app.

**Comment by r3d9u11** [comment]
ok, thank you

**Comment by r3d9u11** [comment]
after some latest updates for neko and haxe it works fine with latest versions of openfl, lime and stablexui!

$haxelib list
...
lime: 2.9.1 git 2.9.0 [dev:/home/r3d9u11/Software/haxelib/lime/git]
openfl: 3.6.0 git 3.6.1 [dev:/home/r3d9u11/Software/haxelib/openfl/git]
stablexui: git [dev:/home/r3d9u11/Software/haxelib/stablexui/git]
...

haxe: 1:3.2.1+dfsg-1~ubuntu14.04.1~ppa2
neko: 2.1.0-3~ubuntu14.04.1~ppa1
libneko0: 2.0.0-4~ubuntu14.04.1~ppa1
libneko2: 2.1.0-3~ubuntu14.04.1~ppa1
