### ISSUE TITLE
can't clear the widget

### ISSUE THREAD

**Issue by LouisSong** [RealyUniqueName/StablexUI#230]
these code can't clear the graphics of a widget.
`var btn:Widget = cast UIBuilder.get("closeButton");
btn.graphics.clear();
`

then i change these to:
`
var btn:Widget = cast UIBuilder.get("closeButton");
settimeout(function(){btn.graphics.clear();},1000);//delay 1 second
`
when i set a delay time,it works.

how can i clear the widget's graphics without a delay time?

**Comment by RealyUniqueName** [comment]
It depends on when you're calling `graphics.clear()`.
If widget was changed somehow and its skin is queued to redraw, it will be redrawn on next frame.
So you need to set skin to `null` if you don't want it to be applied automatically.

**Comment by LouisSong** [comment]
Thanks for your help.when i set skill to null after `gpachiscs.clear(),` it works well now.
