### ISSUE TITLE
tween panel issue

### ISSUE THREAD

**Issue by LouisSong** [RealyUniqueName/StablexUI#233]
I have a panel ,It's a Widget contains a Button(this button's init width is 100,its label's width is 68),when I tween this panel from corner to the center of the stage,and scale from 0.1 to 1.the Button's label will be changed to 84,then the button's label is not In the center of the button.how to solve this problem?

code:
`panel.scaleX = panel.scaleY = 0.1;
tween(panel,{scaleX:1;scaleY:1,x:400,y:300});`

before tween:
button.width : 100;
button.label.width: 68;
button.label.x = 18;

after tween:
button.width:100;
button.label.width:84;
button.label.x = 8;

**Comment by RealyUniqueName** [comment]
Try using `w` property instead of `width`.

**Comment by RealyUniqueName** [comment]
Also you should tween `left` and `top` instead of `x` and `y`

**Comment by LouisSong** [comment]
I found that when set scaleX of a sprite,the textfield's width will be changed,this caused the problem.thank you
