### ISSUE TITLE
Options.set_options causes recursion

### ISSUE THREAD

**Issue by meerfolk** [RealyUniqueName/StablexUI#237]
When you need to set value in options after you set options. And your handler of WidgetEvent.CHANGE should set new value to options it causes recursion, because set_options function set _selectedIdx to 0 and set__selectedIdx function dispatch WidgetEvent.CHANGE.

**Comment by RealyUniqueName** [comment]
```haxe
var options:Options = ...
options.setOptionsSilently([['lion', 1], ['camel', 2], ['elephant', 3]]);
```
