### ISSUE TITLE
scroll bars not working in html5

### ISSUE THREAD

**Issue by hopewise** [RealyUniqueName/StablexUI#241]
Kindly see how scrollbars looks like in Flash target:
![screen shot 2016-10-21 at 6 01 16 pm](https://cloud.githubusercontent.com/assets/1061157/19603134/aef6ab1c-97b8-11e6-908e-c58ac588936b.png)

However, in html5 target, I got this result:
![screen shot 2016-10-21 at 6 01 48 pm](https://cloud.githubusercontent.com/assets/1061157/19603155/c6a1ba04-97b8-11e6-9684-179717d4843d.png)

In html5; the scrollable area can still be scrolled by dragging, but the scroll bars are not showing like in flash target.

Would you please enlighten me? what shall I do to make it work on html5?

I tried to hard code hScroll and hBar.visible to true, but still invisible.. your help is appreciated!

**Comment by RealyUniqueName** [comment]
which versions of haxe, lime, openfl and StablexUI do you use?

**Comment by RealyUniqueName** [comment]
also would be grade if you can provide a minimal project to rerpoduce this issue.

**Comment by hopewise** [comment]
Versions I use:
```
lime: [3.3.0]
openfl: [4.2.0]
perf.js: [1.1.8]
stablexui: [1.1.5]

$ haxe -version
3.3.0
```
Its hard to provide a minimal project code, I will try though..

**Comment by hopewise** [comment]
Oh, I found it, I had a conditional compilation flag:

> #if (flash||windows)
> Scroll_Bar_Dim = Utils.DPS(25);
> #else
> Scroll_Bar_Dim = Utils.DPS(0);
> #end

Sorry, it's my fault, its been a long time before I decided to work on html5 target, therefor, I forgot about the `defaults.xml` for style which has:

```
<LabScroll>
		<Default
		dragScroll="false"
		widthPt="100"
		hBar-slider-skinName="'componentsSlider'"
		hBar-skinName="'componentsSliderBar'"
		hBar-h="Main.Scroll_Bar_Dim"
		hBar-slider-h="Main.Scroll_Bar_Dim- Utils.DPS(2)"
		skin:Paint-color   = "0xbbbbbb"
		/>

    </LabScroll>


```
