### ISSUE TITLE
Text setter causes a bug in html5

### ISSUE THREAD

**Issue by hopewise** [RealyUniqueName/StablexUI#243]
In html5, I found that in `Text.hx` at:

    @:noCompletion private function set_text(txt:String) : String {

    // this would cause a bug in html5 when txt is numeric
    this.label.text = txt;

This would cause an error in [TextEngine.hx ](https://github.com/openfl/openfl/blob/064b924b352f6db76370172eac3cacbdc5ce9369/openfl/_internal/text/TextEngine.hx#L652)of openfl, for ex:

    project.js:83729 Uncaught TypeError: this.text.indexOf is not a function

Because `this.text` is simply a numeric not string.

So, I fixed it by explicitly setting openfl `TextField` of openfl to string, like this:

    @:noCompletion private function set_text(txt:String) : String {
     
    // convert to string
    this.label.text = Std.string(txt);

Thanks for great library 👍

**Comment by RealyUniqueName** [comment]
Sorry for the late response. 
Commited your fix to master.
Thanks for investigation!

**Comment by hopewise** [comment]
You are welcome :)
