### ISSUE TITLE
something wrong with overriding onResize

### ISSUE THREAD

**Issue by r3d9u11** [RealyUniqueName/StablexUI#244]
Hi. When I try to override widget's method onResize it haven't effect:

Haxe: 3.2.1
Target: -neko and -cpp
StablexUI: latest from git

Custom Class:
```
...
class Wcls extends Widget {
	public function new () { super(); trace(111); }
	override public function onResize () : Void trace(123123123);
}
```

Main.hx:
```
...
class Main extends Sprite {
	public function new () {
		super ();
		
		var wgt = new Wcls();
		wgt.w = 100;
	}
}
```

my custom method was not called (but was called original empty method Widget.onResize)

Check it, please.
Thanks.

**Comment by RealyUniqueName** [comment]
You need to use `UIBuilder.create(Wcls)` instead of `ne wWcls()`. Try it and let me know if problem still exists.

**Comment by r3d9u11** [comment]
Yes, it works. But was found this bug for RTXml. I'll open new issues.

Thank you.
