### ISSUE TITLE
problem with listeners

### ISSUE THREAD

**Issue by meerfolk** [RealyUniqueName/StablexUI#248]
When you add listener on Bmp instance or on Box Instance without skin, it don't handle. But it handle when you add skin. This problem started from openfl 4.3.0 (haxe 3.3.0)

**Comment by RealyUniqueName** [comment]
Which target? 
Please provide a minimal project (or at least example xml)

**Comment by meerfolk** [comment]
example https://github.com/meerfolk/stablexuiExample. stablexui_git in project.xml is the stablexUI installed with "haxelib git". I have this problem on html5 target.

**Comment by RealyUniqueName** [comment]
This is an [OpenFL bug](https://github.com/openfl/openfl/issues/1335)

**Comment by meerfolk** [comment]
I remember something like that. Thanks for your help.

**Comment by RealyUniqueName** [comment]
This issue if now fixed in OpenFL git repo.
