### ISSUE TITLE
can't to change state-* properties

### ISSUE THREAD

**Issue by r3d9u11** [RealyUniqueName/StablexUI#252]
Hi. I trying to change state properties of dynamically generated checbox:

```
package;

import openfl.display.Sprite;

class Main extends Sprite {
	public function new () {
		super ();
		
		var cb = new ru.stablex.ui.widgets.Checkbox();
		
		cb.states.get("up").text = "UP";
		cb.states.get("down").text = "DOWN";
		
		this.addChild(cb);
	}
}
```

but I see a blank screen.

Linux Mint 18 x16
latest StablexUI from git
openfl 4.4.1
lime 3.4.1
haxe 3.2.1
neko 2.1.0

targets: neko and cpp

Any ideas?
Thanks.

**Comment by RealyUniqueName** [comment]
Try `UIBuilder.create(CheckBox)` instead of invoking constructor directly

**Comment by r3d9u11** [comment]
changed to

```
package;

import openfl.display.Sprite;

class Main extends Sprite {
	public function new () {
		super ();
		
		var cb = ru.stablex.ui.UIBuilder.create(ru.stablex.ui.widgets.Checkbox);
		
		cb.states.get("up").text = "UP";
		cb.states.get("down").text = "DOWN";
		
		this.addChild(cb);
	}
}
```

but without effect
I see the blank screen

**Comment by RealyUniqueName** [comment]
Did you invoke `UIBuilder.init()` somewhere?

**Comment by r3d9u11** [comment]
Ah, sorry, I've missed it.
I changed source to:
```
package;

import openfl.display.Sprite;

class Main extends Sprite {
	public function new () {
		super ();
		
		ru.stablex.ui.UIBuilder.init();
		
		var cb = ru.stablex.ui.UIBuilder.create(ru.stablex.ui.widgets.Checkbox);
		
		cb.states.get("up").text = "UP";
		cb.states.get("down").text = "DOWN";
		
		this.addChild(cb);
	}
}
```
but it also have not effect

![123](https://cloud.githubusercontent.com/assets/15020827/20826127/d8d127c8-b879-11e6-9fa1-8893bf9670a6.png)

**Comment by r3d9u11** [comment]
just needed to call method updateState() manually.

is it possible to call this method automatically after status changed?

**Comment by RealyUniqueName** [comment]
That should be called automatically when creating UI via xml.
I will try to make it work without xml later this week.

**Comment by r3d9u11** [comment]
Thanks!
