### ISSUE TITLE
Packaging a release?

### ISSUE THREAD

**Issue by hopewise** [RealyUniqueName/StablexUI#253]
In HTML5 target, I have lots of xml files for the UI in `assets/stablexui` folder which are all copied to the /html5/release/bin/assets/stablexui

All those files are loaded before starting the app, the question is, aren't those xml files are already within the resulted app's javascript file after compilation? what do you recommend?

**Comment by RealyUniqueName** [comment]
If you are not using `RTXml` with those files,  then you can move them out of `assets` directory or add `exclude="assets/stablexui"` to assets tag in OpenFL project xml.

**Comment by hopewise** [comment]
thanks, here is how I did it:
    <assets path="assets" rename="assets" exclude="stablexui" />
