### ISSUE TITLE
Type casting in RTXml

### ISSUE THREAD

**Issue by r3d9u11** [RealyUniqueName/StablexUI#255]
Hi. Is it possible to add support type casting to RTXml?
For example now code `"cast(obj, Widget)"` will throw error `EUnknownVariable(cast)`.

Thanks.

**Comment by r3d9u11** [comment]
issue moved to hscript: https://github.com/HaxeFoundation/hscript/issues/58

**Comment by RealyUniqueName** [comment]
Sorry, i somehow missed this issue.
It's indeed a hscript issue. Once implemented in hscript, it should become immediately available in RTXml.
