### ISSUE TITLE
visual builder (duplicate)

### ISSUE THREAD

**Issue by r3d9u11** [RealyUniqueName/StablexUI#256]
Hi. The first pre-release of visual gui-builder is comming out!

Many thanks for your awesome and flexible (and really cross-platform) library, your answers and help!
Also many thanks Artur Makhonko for some help and inspiration ([discussion](https://groups.google.com/forum/#!topic/stablexui/fv6idgAokOY) and his [project](http://momingmy.tk/index.cgi?page=stablexui))!

[Direct link](https://github.com/r3d9u11/StablexUI-Designer)

**Comment by RealyUniqueName** [comment]
It's a big step forward! Haxe really lack visual UI design tools atm.

I've managed to run it with Haxe 3.2.1 (didn't work with 3.4.0), but trying to save/load crashes the app on Ubuntu 16.04. I guess it's an issue of `systools` lib.

**Comment by r3d9u11** [comment]
I have some troubles with systools and linux Mint, too (my issue https://github.com/waneck/systools/issues/35).
I think that Ubuntu uses Unity by default DE, but systools needed GTK.

Now I search other library with native dialogs.

Thank for your interest and evaluation. I hope that this project will be useful.

**Comment by r3d9u11** [comment]
latest SUID works fine now for haxe 3.4.0, too
