### ISSUE TITLE
rtxml can't find StablexUI classes

### ISSUE THREAD

**Issue by r3d9u11** [RealyUniqueName/StablexUI#260]
Hi. After upgading of my haxelib-repo RTXml can't find standard classes of StablexUI.

For example:
`<Button text="$Suid.castType($this, ru.stablex.ui.widgets.Button).name + '_BtnText'"/>`
will be failed with error `Uncaught exception - EUnknownVariable(ru)`

or:
`<Button text="$Suid.castType($this, Button).name + '_BtnText'"/>`
will be failed with error `Uncaught exception - EUnknownVariable(Button)`

target: neko
os: Linux Mint 18.1 x64
```
$ haxelib list
actuate: [1.8.7]
box2d: [1.2.3]
format: [3.3.0]
hscript: [2.0.7]
hvm: [0.0.2]
hxcpp: [3.4.43] 3.4.2
layout: [1.2.1]
lime-samples: [3.4.0]
lime-tools: [1.5.7]
lime: 3.6.0 [3.6.2] 3.5.2 3.6.1
openfl-native: [1.4.0]
openfl-samples: [4.5.1]
openfl-tools: [1.0.10]
openfl: 4.5.2 4.5.3 [4.6.0]
stablexui: git [dev:/home/username/.haxelib_repo/stablexui/git]
```

test sample attached [here](https://github.com/RealyUniqueName/StablexUI/files/723420/testRtxml.zip)
Thanks.

**Comment by RealyUniqueName** [comment]
You should use standard StablexUI widgets without package: `text="$Suid.castType($this, $Button).name"`.

**Comment by r3d9u11** [comment]
Thanks for hint, it works!
