### ISSUE TITLE
repeated event calling

### ISSUE THREAD

**Issue by r3d9u11** [RealyUniqueName/StablexUI#261]
Hi. When I trying to change value for widgets Options, then event WidgetEvent.CHANGE will be fired 2 times.

Main.hx:
```
package;

import openfl.display.Sprite;

import ru.stablex.ui.*;
import ru.stablex.ui.events.*;
import ru.stablex.ui.skins.*;
import ru.stablex.ui.widgets.*;

class Main extends Sprite {
	public function new () {
		super ();
		
		UIBuilder.init();
		
		var i = 0;
		
		var list:Array<Array<Dynamic>> = [ ['asd', null], ['qwe', 2], ['zxc', 3] ];
		
		var opts = UIBuilder.create(Options);
		opts.addEventListener(WidgetEvent.CHANGE, function (e:Dynamic) trace('CHANGED index ${i++}!!!'));
		
		opts.options = list;
		
		this.addChild(opts);
	}
}
```
event will fire once on after list will be filled:
`CHANGED index 0!!!`
but one changing of value to 'qwe' will display:
```
CHANGED index 1!!!
CHANGED index 2!!!
```

Thanks.

**Comment by RealyUniqueName** [comment]
That happened because `Options` is derived from `Text` which now dispatches `CHANGE` event on changing text )
I changed `Text` to dispatch `WidgetEvent.TEXT_CHANGE`, now double event on `Options` is fixed.
