### ISSUE TITLE
Get path for UIBuilder.init and UIBuilder.regSkins from variable

### ISSUE THREAD

**Issue by r3d9u11** [RealyUniqueName/StablexUI#265]
Hi. I'm not strong in macros yet and I need a little hint: is there way to get value from custom variable and set it as path for UIBuilder.init and UIBuilder.regSkins?

for example:
```
var dir:String = ".../my/own/path/directory";

var defaults:String = Path.join([dir, "defaults"]);
var skins:String = Path.join([dir, "skins", "skin.xml"]);

UIBuilder.init(defaults);
UIBuilder.regSkins(skins);
```

where the value of variable "dir" is known at macro-time

Thanks.

**Comment by RealyUniqueName** [comment]
There is no way to use a custom var for this.
The best StablexUI can achieve is setting default path by some (not yet implemented) additional call:
```haxe
UIBuilder.baseDir('.../my/own/path/directory');
UIBuilder.init('defaults.xml'); //.../my/own/path/directory/default.xml is used
UIBuilder.init('skins.xml'); //.../my/own/path/directory/skins.xml is used
```

**Comment by r3d9u11** [comment]
I have a lille idea: https://github.com/r3d9u11/StablexUI/commit/a73a980de0896e328343d4f91f53f73fc4de38ab

this commit allow to use custom variables at macro-time (for path and for content of xml).

what do you think about it?

**Comment by RealyUniqueName** [comment]
It's nice, but what other applications can have such "custom vars" except setting a directory?
If that's the only use-case I prefer "baseDir" solution.

**Comment by r3d9u11** [comment]
One of examples: I have collection of skins, who used in several projects.

If I will use baseDir, then UIBuilder, I think, will search skins, default, and UI-xml in one baseDir. In that situation variable baseDir can't help, because must have a several different path: baseDir of current UI-project, baseDir of skins/defaults collection. And if very long paths to baseDirs will be defined once in target project, It will look nicer and easy to change and fix it, when it needed.

Also existence of vars can add more flexibility for library, because XML can be used as "templates".
