### ISSUE TITLE
Button label color

### ISSUE THREAD

**Issue by frankhdz** [RealyUniqueName/StablexUI#266]
This is not so much an issue but a question. How do you set the label color in a button? I have been looking for documentation on this but none seems to be available.

**Comment by RealyUniqueName** [comment]
Using xml:
```xml
<Button format-color="0xFF0000" text="'Hit me'"/>
```
Using code:
```haxe
var btn = UIBuilder.create(Button, {
    format : { color : 0xFF0000 },
    text : "Hit me"
});
```

**Comment by frankhdz** [comment]
I found it in the docs just as you posted. Thanks!
