### ISSUE TITLE
image-src at runtime

### ISSUE THREAD

**Issue by r3d9u11** [RealyUniqueName/StablexUI#267]
Hi. When I have an error with an RTXml, when I try to set image-src as path to file:
```
...
states-up-ico-skin:Img-src="($Path.join([%CWD, 'presets/default/img/checkbox_unchecked.png']))"
...
```
but, this sample already works for UIBuilder.

as workaround I'm using BitmapData:
```
...
states-up-ico-skin:Img-bitmapData="$BitmapData.fromFile($Path.join([%CWD, 'presets/default/img/checkbox_unchecked.png']))"
...
```

But is it possible to resolve error for the property "Img-src" and RTxml? Thanks.

**Comment by RealyUniqueName** [comment]
Please, post a full project example so i can reproduce your issue.

**Comment by r3d9u11** [comment]
sorry, with UIBuilder failed, too.
[here](https://github.com/RealyUniqueName/StablexUI/files/750464/test.zip) sample with both varianth of xml.

**Comment by RealyUniqueName** [comment]
It's because `src` is used as an argument to `openfl.Assets.getBitmapData()`, but you didn't add that file to assets in your `project.xml`

**Comment by r3d9u11** [comment]
I'll try to change assets, thanks for hint!
