### ISSUE TITLE
Options selecting option does not update the selected option

### ISSUE THREAD

**Issue by frankhdz** [RealyUniqueName/StablexUI#269]
Clicking the an option does not display the selection clicked.

```
<Widget w="1024" h="800" top="20" >
<Text text="'Invoice Status'"  format-size="18"  widthPt="45"/>
				                 <Options
							        w = "100"
							        h = "30"

							        skinName="'seeborder'"
							        skin:Paint-border = "1"
			        				skin:Paint-borderColor = "0x0000FF"
							        options = "[['Open', 1], ['Closed', 2], ['Pending', 3]]"
							        optionDefaults = "'option'"
							        box-skin:Paint-alpha = "0.9"
							    />

</Widget>
```

my code:

`package views.invoices;

import openfl.display.Sprite;
import Main;
import ru.stablex.ui.*;
import ru.stablex.ui.UIBuilder;
import ru.stablex.ui.widgets.Widget;
import ru.stablex.ui.widgets.Text;
import ru.stablex.ui.widgets.HBox;
import ru.stablex.ui.widgets.Box;
import ru.stablex.ui.widgets.Options;
import ru.stablex.ui.widgets.Button;
import openfl.events.MouseEvent;

class MyClass{

public function new(){
		super();

		UIBuilder.init('Assets/ui/defaults.xml');	//add the defaults path to set font universally	
		var ui = UIBuilder.buildFn('Assets/ui/invoicenewui.xml')();
		this.addChild(ui);//load the XML UI

}

`

As you can see I am simply loading the UI XML. But the Option selection is not working for me.

**Comment by RealyUniqueName** [comment]
Try updating StablexUI

**Comment by frankhdz** [comment]
Ok it seems that is all I needed thanks!
