### ISSUE TITLE
How to pass param to included xml file?

### ISSUE THREAD

**Issue by hopewise** [RealyUniqueName/StablexUI#271]
I have this case:

```
<?xml version="1.0" encoding="UTF-8" ?>
<VBox name="'relay'" defaults="'Default,ComponentProperties'" heightPt="100">

	<!--On resistance-->
	<meta:include src="assets/stablexui/fields/resistance.xml" />

	<!--Off resistance-->
	<meta:include src="assets/stablexui/fields/resistance.xml" />

	<!--Coil resistance-->
	<meta:include src="assets/stablexui/fields/resistance.xml" />

</VBox>
```

So, I am using the same `resistance.xml` file for multiple cases, can I pass a var or param so that `resistance.xml` gets aware where it's being used?

**Comment by RealyUniqueName** [comment]
I think Xml Arguments of "parent" document should be available for included one [see "Xml Arguments" section](http://ui.stablex.ru/doc/#manual/04_Advanced_XML.html)

Another option is to create an [Xml based class](http://ui.stablex.ru/doc/#manual/12_XML_based_classes.html) of your `resistance.xml` and then extend it:
```haxe
class Resistance extends ResistanceXml {
    public var on:Bool = true;
}
```
In `resistance.xml`:
```xml
<Widget name="'root-of-resistance'" visible="this.on">
....
</Widget>
```
Then register your `Resistance` class with `UIBuilder.regClass()` and use it in xml:
```xml
<VBox name="'relay'" defaults="'Default,ComponentProperties'" heightPt="100">
    <Resistance on="true"/>
    <Resistance on="false"/>
</VBox>
```

**Comment by hopewise** [comment]
Thank you

**Comment by hopewise** [comment]
Or, to override ui events of `resistance.xml` in `Resistance ` that extends `ResistanceXml `?

**Comment by RealyUniqueName** [comment]
I don't understand your question.

**Comment by hopewise** [comment]
I tried to register Resistance:
```
package;
import ru.stablex.ui.UIBuilder;
class Init{
    macro static public function registerClasses () : Void{
        UIBuilder.regClass('com.clientside.ui.Resistance');
	UIBuilder.buildClass("src/ui/custom_resistance.xml", "com.clientside.ui.ResistanceXML");
  }
}
```
in my build file:

    <compilerflag name="--macro Init.registerClasses()" />

but, I get this error:

>     /usr/local/lib/haxe/lib/stablexui/1,2,1/src/ru/stablex/Err.hx:18: Widget class is not registered: com.clientside.ui.Resistance


com.clientside.ui.Resistance.hx:

```
package com.clientside.ui;
class Resistance extends com.clientside.ui.ResistanceXML {
    public var on:Bool = true;
}
```

inside com.clientside.ui.ResistanceXML.hx:

    <com.clientside.ui.Resistance name="true"/>

**Comment by hopewise** [comment]
Ok, I will try to make it clear:

> src/com/clientside/ui/Resistance.hx:

```
package com.clientside.ui;
class Resistance extends com.clientside.ui.ResistanceXML {
    public var caption:String = "samir";
}
```
I register widget as:
```
macro static public function registerClasses () : Void{
        UIBuilder.buildClass("src/ui/custom_resistance.xml", "com.clientside.ui.ResistanceXML");
        UIBuilder.regClass('com.clientside.ui.Resistance');
}
```
>in src/ui/custom_resistance.xml:
```
<Text name="'resistance_label'" defaults="'Default,Property'" text="this.caption" />
```
I tried to include the new widget as:

    <Resistance caption="'On resistance'"/>

but I got error:
     com.clientside.ui.ResistanceXML has no field caption

although `caption` is a property in the `Resistance.hx` above,

**Comment by hopewise** [comment]
I am opening another issue for consistency.
