### ISSUE TITLE
InputText not taking spaces

### ISSUE THREAD

**Issue by hopewise** [RealyUniqueName/StablexUI#277]
If I type into InputText, I notice that it does not accept space character, how can I debug this issue?

**Comment by hopewise** [comment]
`restrict` property of label is null, thus, it should allow spaces.. but it does not..

**Comment by RealyUniqueName** [comment]
Sorry for the late reply. I will check it asap.

**Comment by RealyUniqueName** [comment]
I checked with [04_arguments sample](https://github.com/RealyUniqueName/StablexUI/tree/master/samples/04_arguments) using Haxe 3.4 and OpenFL 6.5.3
It works fine with spaces. Which versions do you use? Can you provide a minimal reproducible sample?

**Comment by hopewise** [comment]
I've finally found the reason behind this, it was an event listener that prevents event provocation, sorry for confusion.
