### ISSUE TITLE
hBar alignment?

### ISSUE THREAD

**Issue by hopewise** [RealyUniqueName/StablexUI#280]
How can I set `hBar` in `Scroll` to appear at top instead of at bottom?
I tried setting its top to zero at creation inside `Scroll` as:

```
this.hBar = UIBuilder.create(Slider, {
            vertical : false,
            top   : 0,
            left     : 0,
            widthPt  : 100,
            h        : 10,
            slider   : {heightPt : 100}
        });
```

I also, tried adding it at zero index as:

    if( this.hBar.parent == null ) this.addChildAt(this.hBar, 0); // instead of 1

but it always shown at bottom..

**Comment by RealyUniqueName** [comment]
Try creating `Scroll` like this:
```haxe
UIBuilder.create(Scroll, {
  hBar: { top: 0 }
});
```

**Comment by hopewise** [comment]
But I am using a custom tag as: `<LabScroll` where `LabScroll` extends `Scroll`

**Comment by hopewise** [comment]
thanks :)
