### ISSUE TITLE
$this.name inside custom widget leads to "Any has no field name"

### ISSUE THREAD

**Issue by yurike** [RealyUniqueName/StablexUI#286]
Project to reproduce:
[ElRage_tests.zip](https://github.com/RealyUniqueName/StablexUI/files/4826379/ElRage_tests.zip)

This line in card.xml produces error:
`<Button name="'attackL'" w="33" h="30" skinName="'btn'" on-click="Card.attack(name, $this.name);"/>`

Latest versions of StablexUI, OpenFL and Haxe

This is from old project, $this.name in this code was working before (some old version of OpenFL and Haxe 3.4.7)

**Comment by RealyUniqueName** [comment]
Please try with the latest StablexUI commit.

**Comment by yurike** [comment]
yep, it is working as expected now. Thanks!
