### ISSUE TITLE
Abstract-backend branch status.

### ISSUE THREAD

**Issue by gfcrba** [RealyUniqueName/StablexUI#287]
Hi, Aleksandr!

I'm trying to bring back to life very old (flash-targeted) project :). We used StablexUI there (many thanks to you!).
But time changed and I'm looking a way with minimal effort move to html5. We now use pixijs as engine. 
The question:
Do you thing `abstract-beckend` is worth trying or it's really old branch?
Thanks again for you UI lib it helped us alot. Long Live Haxe ;)

**Comment by RealyUniqueName** [comment]
Hi.
It's very old and it's not worth trying.

**Comment by gfcrba** [comment]
Thanks for your reply!
