### ISSUE TITLE
RTXML does not support meta:include?

### ISSUE THREAD

**Issue by darcyg** [RealyUniqueName/StablexUI#47]
RTXML does not support meta:include?
Error message:
Class is not registered for runtime xml:meta:include

**Comment by hopewise** [comment]
After 5 years, is this limitation still on? What do you recommend to overcome this limitation please?

**Comment by RealyUniqueName** [comment]
Unfortunately I abandoned the development of STablexUI. 
You can create a custom widget with an `xml` property. And make that widget load that xml. 
Something like this:
```haxe
class RTInclude extends Widget {
  public var xml(never,set):String;
  //<...>
  override public function refresh() {
    var index = parent.getChildIndex(this);
    parent.addChildAt(RTXml.buildFn(xml)(), index);
    parent.removeChild(this);
  }
}
```
and then in xml:
```xml
<RTInclude xml="'path/to/ui.xml'"/>
```

**Comment by hopewise** [comment]
Thanks

**Comment by hopewise** [comment]
@RealyUniqueName I have managed to load the UIs at the `src` of `meta:include`, and I got the complete xml, however, it seems that hscript interpreter could not recognize my class `Main` as I got error when tried to build the xml with `RTXml.buildFn` :

```
js__$Boot_HaxeError {val: {…}, stack: "Error: EUnknownVariable(Main)↵    at hscript_Inter
```

I used to import my class `Main` at the same place where I build the xml but its not working with RTXml even when I import the `Main` class

Any idea?
Thanks for your support 👍

**Comment by RealyUniqueName** [comment]
You need to `RTXml.regClass(CustomWidgetClass)` to make it available in RTXml.

**Comment by hopewise** [comment]
💚

**Comment by hopewise** [comment]
I just tried to register the class as:

    RTXml.regClass(Main);

but I still get the same error..

    js__$Boot_HaxeError {val: {…}, stack: "Error: EUnknownVariable(Main)↵    at hscript_Inter

What could be wrong?

**Comment by RealyUniqueName** [comment]
Are you sure it gets executed before `RTXml.buildfn()`?

**Comment by hopewise** [comment]
Yes, here is my code:

```
var properties:ViewStack = UIBuilder.get('properties').as(ViewStack);            
RTXml.regClass(Main);
RTXml.regClass(Utils);            
var widget:Widget = RTXml.buildFn(xml.toString())();
properties.addChild(widget);
```
and I also include hscript in my project as:

```
<haxelib name="hscript"/>
<haxelib name="stablexui"/>
```

**Comment by RealyUniqueName** [comment]
I'm out of ideas. Perhaps I could help you if you provide a complete sample to reproduce.

**Comment by hopewise** [comment]
My project is big, can you please prepare a minimal working example I can depend on?

**Comment by hopewise** [comment]
Luckily I could create a minimal code to produce the error here: https://github.com/hopewise/stabelxui-test-RTXml

I am very interested to hear from you!

**Comment by hopewise** [comment]
@RealyUniqueName did you get the chance to see the sample code?
I have noticed I've got the same error for your library native components, and I have succefully registered them as [here](https://github.com/hopewise/stabelxui-test-RTXml/blob/master/Source/Main.hx#L20)  however, I could not [register](https://github.com/hopewise/stabelxui-test-RTXml/blob/master/Source/Main.hx#L24) my own [classes](https://github.com/hopewise/stabelxui-test-RTXml/tree/master/Source/com/clientside/main)

why my classes are not registrable?

**Comment by RealyUniqueName** [comment]
Not yet. I was on a small vacation. I'll take a look in the nearest days.

**Comment by hopewise** [comment]
Thanks, my lab will load much faster when I sort this issue, as I currently preload more than 20 UI xmls at booting!

**Comment by hopewise** [comment]
Hello @RealyUniqueName, I like to know please if you got the chance to see the sample code?

**Comment by RealyUniqueName** [comment]
Not yet, sorry. 
I hope I'll have a time for it on Monday or Tuesday.

**Comment by hopewise** [comment]
No worries! : ) I will be working on other tasks.. thank you

**Comment by hopewise** [comment]
Hello, I just like to know please if you got the chance to see the source code? It's straight and minimal code to introduce the issue..

**Comment by RealyUniqueName** [comment]
Sorry for the long delay.
Please try with this branch: https://github.com/RealyUniqueName/StablexUI/tree/RTXml.regClass-fix

**Comment by hopewise** [comment]
Thanks! that has worked 😺 what was the issue ?
Will you be deploying new release for this fix?

**Comment by RealyUniqueName** [comment]
> what was the issue ?

I don't remember why, but I made RTXml to add prefix `__ui__` to each registered class :)
So instead of `Main` it was available as `__ui__Main`

> Will you be deploying new release for this fix?

I've submitted v1.2.3 on haxelib

**Comment by hopewise** [comment]
Thanks @RealyUniqueName 👍
